on:
  release:
    types: [created]
name: Build & Release
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: any
      - uses: actions/checkout@master
      - name: build with ming
        run: |
          go build -v -buildmode=c-archive .
          gcc -o tst main.c main.a -lWinMM -lntdll -lWS2_32
          gcc -shared -pthread -o main.dll main.c main.a -lWinMM -lntdll -lWS2_32      
      - name: list
        run: |
          dir 
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dll-files
          path: |
            main.*
            go.mod
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dll-files
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goarm: 5
          # goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
          # project_path: "./cmd/test-binary"
          # binary_name: "test-binary"
          extra_files: main.dll main.h
      # - name: Create release
      #   uses: Roang-zero1/github-create-release-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload release artifacts
      #   uses: Roang-zero1/github-upload-release-artifacts-action@v2
      #   with:
      #     args: "main.dll main.h"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
